// Action Types
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAIL = "CREATE_NEW_USER_FAIL";

export const CREATE_DATA = "CREATE_DATA";
export const CREATE_DATA_SUCCESS = "CREATE_SUCCESS";
export const CREATE_DATA_FAIL = "CREATE_FAIL";

export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";

export const MODIFY_DATA = "MODIFY_DATA";
export const MODIFY_DATA_SUCCESS = "MODIFY_DATA_SUCCESS";
export const MODIFY_DATA_FAIL = "MODIFY_DATA_FAIL";

export const DELETE_DATA = "DELETE_DATA";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL";